name: Workflow
on:
  push:
    branches:
      - feature-clase1

jobs: 
  SAST:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set Enviroment Variables
        run: echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Validate and Configure build.gradle
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          if [ -f "build.gradle" ]; then
            echo "Encontro el archivo build.gradle"
            echo "Verificando configuracion del plugin sonar"
            if ! grep -q 'id "org.sonarquebe" version "3.3"' build.gradle; then
              sed -i "/id 'java'/a\\  id 'org.sonarquebe' version '3.3'" build.gradle
              echo "pluggin de sonarcloud añadido a build.gradle"
              cat build.gradle
            else
              echo "pluggin de sonarcloud ya estaba configurado en build.gradle"
              cat build.gradle
            fi

          else
            echo "NO encontro el archivo build.gradle"
            exit 1
          fi